import Head from 'next/head'
import LandingPageHero from '../components/sections/landing_page/hero/hero';

import NavBar from '../components/navbar/Navbar';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Swiss DAO</title>
        <meta name="Swiss Web3 Community" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>

      <LandingPageHero/>
 

      
    </div>
  )
}
